version: '3.8'

services:
  api:
    build:
      context: ./api/CarRepairApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "2137:2137"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 