version: "3.9"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    hostname: "mssql"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=f5bac7b9-f11a-416e-b90b-6c7f601e6cf2
